version: '3.8'

services:
  geoserver:
    image: docker.osgeo.org/geoserver:2.22.5 # 镜像:版本号
    container_name: docker_geoserver #容器名称
    restart: always #总是重启
    ports: # 端口映射
      - 8081:8080
    environment: # 环境变量
      CORS_ENABLED: true # 支持跨域
      INSTALL_EXTENSIONS: true # 安装插件
      STABLE_EXTENSIONS: "importer,printing,monitor,params-extractor,css,vectortiles" # 插件信息
    volumes: # 数据卷，目录挂载数据文件和配置文件
      - /data/geoserver/libs:/opt/additional_libs # 本地jar包挂载到容器里，容器启动后将jar包复制到/opt/apache-tomcat-9.0.75/webapps/geoserver/WEB-INF/lib/，然后重启容器安装hbase、geomesa插件
      - /data/geoserver/data:/opt/geoserver_data # 容器里的数据挂载到本机