version: '3.8'

services:
  supervisor2:
    image: storm
    container_name: supervisor2
    hostname: supervisor2
    command: storm supervisor
    restart: always
    ports:
      - 6700:6700
      - 6701:6701
      - 6702:6702
      - 6703:6703
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /data/storm/storm.yaml:/conf/storm.yaml
      - /data/container/storm/supervisor2/data:/data
      - /data/container/storm/supervisor2/logs:/logs
    extra_hosts:
      - nimbus:192.168.0.1
      - zoo1:192.168.0.1
      - zoo2:192.168.0.2
      - zoo3:192.168.0.3
      - supervisor1:192.168.0.1
      - supervisor2:192.168.0.2
      - supervisor3:192.168.0.3