version: '3.8'

services:
  zoo3:
    image: zookeeper
    container_name: zoo3
    restart: always
    hostname: zoo3
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    volumes:
      - /data/container/zoo/zoo3/data:/data
      - /data/container/zoo/zoo3/datalog:/datalog
    environment:
      TZ: Asia/Shanghai
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181
    extra_hosts:
      - zoo1:192.168.0.1
      - zoo2:192.168.0.2
      - zoo3:192.168.0.3

  supervisor3:
    image: storm
    container_name: supervisor3
    hostname: supervisor3
    command: storm supervisor
    restart: always
    ports:
      - 6700:6700
      - 6701:6701
      - 6702:6702
      - 6703:6703
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /data/storm/storm.yaml:/conf/storm.yaml
      - /data/container/storm/supervisor3/data:/data
      - /data/container/storm/supervisor3/logs:/logs
    extra_hosts:
      - nimbus:192.168.0.1
      - zoo1:192.168.0.1
      - zoo2:192.168.0.2
      - zoo3:192.168.0.3
      - supervisor1:192.168.0.1
      - supervisor2:192.168.0.2
      - supervisor3:192.168.0.3