version: '3.8'

services:
  nginx:
    image: nginx # 镜像
    container_name: nginx #容器名称
    restart: always #总是重启
    network_mode: host # host网络模式，nginx容器与宿主机共享网络，这样监听任意端口可以不用指定，否则要在ports指定才能访问
    ports: # 端口映射
      - 80:80
    environment: # 环境变量
      TZ: Asia/Shanghai # 时区
    volumes: # 数据卷，目录挂载数据文件和配置文件
      - /data/nginx/nginx.conf:/etc/nginx/nginx.conf # 挂载主配置文件，覆盖容器的配置文件
      # - /data/nginx/conf:/etc/nginx/conf.d/ # 挂载配置目录，目录中的配置文件内容为server定义，容器内有default.conf来监听80，如果挂载此目录，外部配置文件需定义80端口对应的server配置
      - /data/nginx/www/:/usr/share/nginx/www # 自定义的资源目录挂载到容器内
      - /data/container/nginx/logs/:/var/log/nginx # nginx日志，持久化到宿主机