version: '3.8'

services:
  broker1:
    image: wurstmeister/kafka # 镜像
    restart: always # 总是重启
    hostname: kafka1 # host名称
    container_name: kafka1 # 容器名称
    ports:
      - 9092:9092 # 端口映射
    environment:
      TZ: Asia/Shanghai # 设置时区
      KAFKA_BROKER_ID: 1 # 设置broker.id
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.0.1:9092 # 注册地址，生产者和消费者使用的地址
      KAFKA_ADVERTISED_HOST_NAME: kafka1 # 设置hostname
      KAFKA_ADVERTISED_PORT: 9092 # 端口
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181 # zk节点信息
    volumes: # 挂载日志
      - /data/container/kafka/kafka1:/kafka/kafka-logs-kafka1
    extra_hosts: # hosts配置
      - zoo1:192.168.0.1
      - zoo2:192.168.0.2
      - zoo3:192.168.0.3

  kafka-manager:
    image: kafkamanager/kafka-manager # 镜像
    container_name: kafka-manager # 容器名称
    restart: always # 总是重启
    ports:
      - 9000:9000 # 端口映射
    environment:
      TZ: Asia/Shanghai # 设置时区
      ZK_HOSTS: zoo1:2181,zoo2:2181,zoo3:2181 # zk节点信息
    extra_hosts: # hosts配置
      - zoo1:192.168.0.1
      - zoo2:192.168.0.2
      - zoo3:192.168.0.3