version: '3.8'

services:
  zoo1:
    image: zookeeper
    container_name: d-zookeeper1
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    volumes:
      - /data/container/zoo/zoo1/data:/data
      - /data/container/zoo/zoo1/datalog:/datalog
    environment:
      TZ: Asia/Shanghai
      ZOO_MY_ID: 1 
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zoo2:12888:13888;2182 server.3=zoo3:22888:23888;2183 # zookeeper节点列表

  zoo2:
    image: zookeeper
    container_name: d-zookeeper2
    restart: always
    hostname: zoo2
    ports:
      - 2182:2182
      - 12888:12888
      - 13888:13888
    volumes:
      - /data/container/zoo/zoo2/data:/data
      - /data/container/zoo/zoo2/datalog:/datalog
    environment:
      TZ: Asia/Shanghai
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=0.0.0.0:12888:13888;2182 server.3=zoo3:22888:23888;2183

  zoo3:
    image: zookeeper
    container_name: d-zookeeper3
    restart: always
    hostname: zoo3
    ports:
      - 2183:2183
      - 22888:22888
      - 23888:23888
    volumes:
      - /data/container/zoo/zoo3/data:/data
      - /data/container/zoo/zoo3/datalog:/datalog
    environment:
      TZ: Asia/Shanghai
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:12888:13888;2182 server.3=0.0.0.0:22888:23888;2183

  broker1:
    image: wurstmeister/kafka # 镜像
    restart: always # 总是重启
    hostname: kafka1 # host名称
    container_name: kafka1 # 容器名称
    ports:
      - 9091:9091 # 端口映射
    environment:
      TZ: Asia/Shanghai # 设置时区
      KAFKA_BROKER_ID: 1 # 设置broker.id
      KAFKA_LISTENERS: PLAINTEXT://kafka1:9091 # 单机运行kafka集群，须添加此项配置，且kafka1不能替换成IP
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.0.1:9091 # 注册地址，生产者和消费者使用的地址
      KAFKA_ADVERTISED_HOST_NAME: kafka1 # 设置hostname
      KAFKA_ADVERTISED_PORT: 9091 # 端口
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2182,zoo3:2183 # zk节点信息
    volumes:
      - /data/container/kafka/kafka1:/kafka/kafka-logs-kafka1
    external_links:
      - zoo1
      - zoo2
      - zoo3

  broker2:
    image: wurstmeister/kafka
    restart: always
    hostname: kafka2
    container_name: kafka2
    ports:
      - 9092:9092
    environment:
      TZ: Asia/Shanghai
      KAFKA_BROKER_ID: 2
      KAFKA_LISTENERS: PLAINTEXT://kafka2:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.0.1:9092
      KAFKA_ADVERTISED_HOST_NAME: kafka2
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2182,zoo3:2183
    volumes:
      - /data/container/kafka/kafka2:/kafka/kafka-logs-kafka2
    external_links:
      - zoo1
      - zoo2
      - zoo3

  broker3:
    image: wurstmeister/kafka
    restart: always
    hostname: kafka3
    container_name: kafka3
    ports:
      - 9093:9093
    environment:
      TZ: Asia/Shanghai
      KAFKA_BROKER_ID: 3
      KAFKA_LISTENERS: PLAINTEXT://kafka3:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.0.1:9093
      KAFKA_ADVERTISED_HOST_NAME: kafka3
      KAFKA_ADVERTISED_PORT: 9093
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2182,zoo3:2183
    volumes:
      - /data/container/kafka/kafka3:/kafka/kafka-logs-kafka3
    external_links:
      - zoo1
      - zoo2
      - zoo3
    

  kafka-manager:
    image: kafkamanager/kafka-manager
    container_name: kafka-manager
    restart: always
    ports:
      - 9000:9000
    external_links: 
      - kafka1
      - kafka2
      - kafka3
    environment:
      ZK_HOSTS: zoo1:2181,zoo2:2182,zoo3:2183