version: '3.8'

services:
  postgres:
    image: postgres:16.2 # 镜像:版本号
    container_name: docker_postgres #容器名称
    restart: always #总是重启
    ports: # 端口映射
      - 5432:5432
    environment: # 环境变量
      TZ: Asia/Shanghai # 时区
      POSTGRES_USER: postgres # 默认用户名
      POSTGRES_PASSWORD: 12345678 # 密码
      POSTGRES_DB: postgres # 初始化db
    volumes: # 数据卷，目录挂载数据文件和配置文件
      - /data/postgres/data:/var/lib/postgresql/data # 自定义的资源目录挂载到容器内
      - /data/postgres/conf/postgres.conf:/etc/postgresql/postgresql.conf # 挂载主配置文件，覆盖容器的配置文件