version: "3.8"

services:
  redis-7003:
    image: redis
    container_name: redis-7003
    restart: always
    ports: 
      - 7003:7003
      - 17003:17003
    volumes:
      - /data/redis-cluster/redis-7003.conf:/usr/local/etc/redis/redis.conf
      - /data/container/redis/7003:/data
    environment:
      TZ: Asia/Shanghai
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-7006:
    image: redis
    container_name: redis-7006
    restart: always
    ports: 
      - 7006:7006
      - 17006:17006
    volumes:
      - /data/redis-cluster/redis-7006.conf:/usr/local/etc/redis/redis.conf
      - /data/container/redis/7006:/data
    environment:
      TZ: Asia/Shanghai
    command: redis-server /usr/local/etc/redis/redis.conf