version: "3.8"

services:
  redis-7001: # 服务名称
    image: redis # 创建容器时所需的镜像
    container_name: redis-7001 # 容器名称
    restart: always # 容器总是重新启动
    network_mode: host # host 网络模式
    ports: # 端口映射
      - 7001:7001
      - 17001:17001
    volumes: # 数据卷，目录挂载
      - /data/redis-cluster/redis-7001.conf:/usr/local/etc/redis/redis.conf
      - /data/container/redis/7001:/data
    environment: #环境变量
      TZ: Asia/Shanghai
    command: redis-server /usr/local/etc/redis/redis.conf # 覆盖容器启动后默认执行的命令

  redis-7002:
    image: redis
    container_name: redis-7002
    network_mode: host
    ports: 
      - 7002:7002
      - 17002:17002
    volumes:
      - /data/redis-cluster/redis-7002.conf:/usr/local/etc/redis/redis.conf
      - /data/container/redis/7002:/data
    environment:
      TZ: Asia/Shanghai
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-7003:
    image: redis
    container_name: redis-7003
    network_mode: host
    ports: 
      - 7003:7003
      - 17003:17003
    volumes:
      - /data/redis-cluster/redis-7003.conf:/usr/local/etc/redis/redis.conf
      - /data/container/redis/7003:/data
    environment:
      TZ: Asia/Shanghai
    command: redis-server /usr/local/etc/redis/redis.conf
  
  redis-7004: 
    image: redis 
    container_name: redis-7004 
    restart: always 
    network_mode: host 
    ports: 
      - 7004:7004
      - 17004:17004
    volumes: 
      - /data/redis-cluster/redis-7004.conf:/usr/local/etc/redis/redis.conf
      - /data/container/redis/7004:/data
    environment:
      TZ: Asia/Shanghai
    command: redis-server /usr/local/etc/redis/redis.conf 

  redis-7005:
    image: redis
    container_name: redis-7005
    network_mode: host
    ports: 
      - 7005:7005
      - 17005:17005
    volumes:
      - /data/redis-cluster/redis-7005.conf:/usr/local/etc/redis/redis.conf
      - /data/container/redis/7005:/data
    environment:
      TZ: Asia/Shanghai
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-7006:
    image: redis
    container_name: redis-7006
    network_mode: host
    ports: 
      - 7006:7006
      - 17006:17006
    volumes:
      - /data/redis-cluster/redis-7006.conf:/usr/local/etc/redis/redis.conf
      - /data/container/redis/7006:/data
    environment:
      TZ: Asia/Shanghai
    command: redis-server /usr/local/etc/redis/redis.conf